[package]
name = "lox-vm"
version = "0.1.0"
authors = ["atsmtat <ssmit004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1.0.7"